name: "apply Harvester sshd_config"
stages:
   initramfs:
     - name: "clear original config"
       commands:
       - |
         sed -i '/### Harvester Config/,$d' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*PermitRootLogin.*\)/#\1/' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*LoginGraceTime.*\)/#\1/' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*AllowGroups.*\)/#\1/' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*AllowAgentForwarding.*\)/#\1/' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*X11Forwarding.*\)/#\1/' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*AllowTcpForwarding.*\)/#\1/' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*MaxAuthTries.*\)/#\1/' /etc/ssh/sshd_config
         sed -i 's/^\([^#]*Subsystem.*sftp\)/#\1/' /etc/ssh/sshd_config
     - name: "append config"
       commands:
       - |
         cat <<EOF >> /etc/ssh/sshd_config
         ### Harvester Config
         PermitRootLogin no
         LoginGraceTime 60
         AllowGroups admin
         AllowAgentForwarding no
         X11Forwarding no
         AllowTcpForwarding no
         MaxAuthTries 3
         EOF
